### ISSUE TITLE
pretrain model on imagenet

### ISSUE THREAD

**Issue by yflv-yanxia** [austingg/MobileNet-v2-caffe#1]
Thank you for your implementation. Have you released any pre-train model on imagenet database

**Comment by austingg** [comment]
@yflv-yanxia  Currently no pre-trained model. caffe has no fast depthwise conv implemention as tensorflow or mxnet, I strongly recommend Using mxnet, pytorch, or tf to reimplement mobilenetv2.  This script is only used for verify the network structure, and maybe in the future, convert a model from other DL Frameworks.

**Comment by austingg** [comment]
@yflv-yanxia  you can reference shicai's mobilenetv2 pretrained model.

**Comment by yflv-yanxia** [comment]
@austingg Thank you!
