### ISSUE TITLE
The model complexity(MAdds) is bigger than that in the paper

### ISSUE THREAD

**Issue by TaojiannanYang** [austingg/MobileNet-v2-caffe#2]
Hi, I compute the the MAdds of your .prototxt, the MAdds is 313M, which is bigger than the MAdds stated in the paper(300M). I can not figure out where went wrong. I think my computation is right(I have used the script to compute other models), and I think your implementation is also right. Do you have any idea about this? Have you computed the MAdds of your implementation? Thanks in advance.

**Comment by austingg** [comment]
@TaojiannanYang  sorry for late. I have checked the tf official mobilenet. The first bottleneck sequence whose expand ratio is 1, have only  depthwise conv and conv linear, no conv 1x1 expand. And the missing conv 1x1's MAdd is about 13M ( 112x112x1x1x32x32).  However, this detailed is not mentioned in the paper.
