### ISSUE TITLE
inception data augmentation helps.

### ISSUE THREAD

**Issue by suiyuteng** [austingg/MobileNet-v2-caffe#3]
Is this data augmentation method mentioned in the “going deep with convolutions” paper?And in training or in testing to do data augmentation. I only use single-crop in picture's center now, so I have a lower accuracy in testing other's models. I often failed to achieve the accuracy mentioned in the paper, so I suspect that is when on the training only use mirror to augment data.

**Comment by austingg** [comment]
@suiyuteng  Yes,  inception series all use that aug. only perform data aug during training stage.  In test stage, only use 256x center crop. 
Many people have reimplemented the paper, you may need further investigation.
