### ISSUE TITLE
Issues about training on caffe

### ISSUE THREAD

**Issue by leochli** [austingg/MobileNet-v2-caffe#5]
Hi Austing,
You said there is not an optimized Depthwise conv layer in caffe. 
I found there're 2 dw conv implementations:

https://github.com/BVLC/caffe/pull/5665/files
https://github.com/yonghenglh6/DepthwiseConvolution

Are they not good enough during your experiment? Or is there any other reasons for not training in caffe?

**Comment by austingg** [comment]
@leochli  Those implementation is slower than tensorflow or MXNet, especially when  use large batch size, such as > 64. So that's not the first choice.
