### ISSUE TITLE
Issues about the dataset

### ISSUE THREAD

**Issue by blueardour** [austingg/MobileNet-v2-caffe#6]
Hi, austingg: 

Thanks for your sharing of the mobilentv2 network. I want to repeat the experiment and hoping to restire the paper accuracy. There are three questions for me about the dataset.
1. Did you employ only the imagenet2012 dataset or also took the imagenet 2016 data when training?
2. When resizing the origin images, did you resize them to fixed 256x256 or 256xN. I hear that the later one might result in better accuracy.
3. How the data augmentation helps for the accrcury? Is there any comparison?

**Comment by austingg** [comment]
@blueardour  I haven't use caffe to reproduce the mobilenetv2 result. 
2. resize to 256xN, and crop 224x224 for network input
3. inception augmentation helps. 

You may reference MXNet's implementation log and scripts.
