### ISSUE TITLE
细节调参

### ISSUE THREAD

**Issue by ujsyehao** [austingg/MobileNet-v2-caffe#8]
1. 请问你可以放出solver.prototxt吗？
2. 第一个batchnorm前的conv使用了bias_term: true，剩余所有的batchnorm前的conv都使用了bias_term: false，请问这样做的依据是什么？
3. 关于scale层的设置，你使用了默认mult参数，即1,1,1,1而mobilenet v1中scale层mult参数为1,0,1,0或者1, 0, 2, 0即不使用decay_mult，请问这样做的原因是什么？

**Comment by austingg** [comment]
@ujsyehao 
1. 现在不建议用caffe训练了。  Tensorflow官方已经放出了模型以及复现脚本。可以参考。
2. 加了bn的conv bias_term 不起作用，具体可以推导下， 设置成false是为了节省点计算， 加上问题也不大。
