### ISSUE TITLE
What is the speed of Mobilenet-v2 running on caffe?

### ISSUE THREAD

**Issue by AlexofNTHU** [austingg/MobileNet-v2-caffe#9]
Using my TitanX(Maxwell), I got 20ms for a 224*224 image inference with batch=1.
How fast could you achieve on caffe?
Thanks,

Alex

**Comment by austingg** [comment]
@AlexofNTHU  sorry， I have not used caffe for a long time.  If you use cuda and cudnn, the inference speed will be much faster than 20 ms. Maybe you need some warmup and get average inference time.
